"""'init'

Revision ID: 30af42cda624
Revises: 265f2e6f6188
Create Date: 2019-01-23 17:00:30.917000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30af42cda624'
down_revision = '265f2e6f6188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'time')
    op.drop_column('topic', 'time')
    op.drop_column('user', 'sign')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sign', sa.VARCHAR(length=30), nullable=True))
    op.add_column('topic', sa.Column('time', sa.VARCHAR(length=60), nullable=True))
    op.add_column('post', sa.Column('time', sa.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
